### ISSUE TITLE
Questions about the paper Log Pruning in Distributed Event-sourced Systems

### ISSUE THREAD

**Issue by YvanZhong** [vs-uulm/debs2018-log-pruning-evaluation#1]
Hello sir,
 
 I have read this paper and have some questions to ask. Because I didn't find other contact information, so I open an issue. 
  

1.  Does log pruning and snapshot means the same? There are four approaches for log pruning. Can they be used for snapshot?
2.  I'm not clear about **the tumbling window approach**. Can you give me more information?
3.  Same to above. Can you give me more information about **the hierarchical approach** ?

Thanks!

Best,
Yvan

**Comment by berb** [comment]
Dear Yvan,

thanks for your message. Regarding your questions:

1.  No, log pruning, checkpointing, and snapshotting are not the same concepts in our event-sourced system model. A checkpoint is a full state that is additionally appended to a log event in order to speed up reconstructions of previous states. A snapshot is a set that contains one state for each event-sourced entity so that the set is consistent. Log pruning is the process of removing entries from an event log. Hence, log pruning is not a mechanism for snapshotting, but it has an effect on checkpointing and the reconstructability for snapshotted states.
2. & 3. Please see the source code of this repository and feel free to ask specific questions to these approaches.
